# Site Settings
name: iamkulbhushansingh blog
description: just my experiences in open source :)
baseurl: ""
url : "https://iamkulbhushansingh.github.io"

# Blog Settings
theme_settings :
  title : Kulbhushan Singh -Algorithm
  favicon : assets/faviconn.ico

  # Profile Settings
  profile :
    image : assets/img/dp.png
    username : Kulbhushan Singh
    description : I am a BCA student in IITM Janakpuri.I am intrested in solving Algorithms. 
    #experience :
      - #start : 11-07-2019 
        #end : present
       # experience : <a href="https://amfoss.in/">amfoss-club</a>
    skills : 
      - skill : HTML5
        value : 60  # Percent value
      - skill : python
        value : 60
      - skill : c++
        value : 80

  # Icons
  icons :
    email:  iamkulbhushansingh@gmail.com
    linkedin:  https//:www.linkedin.com/iamkulbhushansingh # Full URL 
    github: iamkulbhushansingh
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: 
    youtube:
    facebook: 
    instagram: i_m_rajput.py

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
